#!/usr/bin/env python
"""
BCI (Bitcoin Cloud Infrastructure)
"""
import subprocess
import os

print ('bci running...')


linode_root_pass = os.getenv('LINODE_ROOT_PASSWORD')
p = subprocess.run("cat ~/.ssh/id_rsa.pub", check=True, shell=True, capture_output=True)
ssh_key = p.stdout.decode().rstrip()
cmd = ["linode-cli", "linodes", "create", "--authorized_keys", ssh_key, "--root_pass", linode_root_pass, 
    "--label", "hwk-newark", "--region", "us-east", "--image", "linode/ubuntu21.10", "--type", "g6-standard-1"]
subprocess.run(cmd, cwd='.', check=True, shell=False)
print ('bci done.')
