name: BCI build and test
on: [push]
env:
  LINODE_ROOT_PASSWORD: ${{secrets.LINODE_ROOT_PASSWORD}}
  LINODE_CLI_TOKEN: ${{secrets.LINODE_CLI_TOKEN}} 
jobs:
  bci-platform-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Build and Test
        run: |
        echo "The LINODE_ROOT_PASSWORD is:${{env.LINODE_ROOT_PASSWORD}}"       
        echo "The LINODE_CLI_TOKEN is:${{env.LINODE_CLI_TOKEN}}"       
        make test-int
      - run: echo "This job's status is ${{ job.status }}."
